/* Write your PL/SQL query statement below */
SELECT T.REQUEST_AT AS "Day", ROUND(AVG(CASE WHEN T.STATUS = 'cancelled_by_driver' OR T.STATUS = 'cancelled_by_client' THEN 1 ELSE 0 END), 2) AS "Cancellation Rate"
FROM TRIPS T JOIN USERS C ON T.CLIENT_ID = C.USERS_ID
JOIN USERS D ON T.DRIVER_ID = D.USERS_ID 
WHERE C.BANNED = 'No' AND D.BANNED = 'No' AND 
TO_DATE(T.REQUEST_AT, 'YYYY-MM-DD') BETWEEN TO_DATE('2013-10-01', 'YYYY-MM-DD') AND TO_DATE('2013-10-03', 'YYYY-MM-DD')
GROUP BY T.REQUEST_AT;